---
- name: Ensure dependency is installed (Ubuntu).
  apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch apt key.
  apt_key:
    url: "{{ filebeat_repo_key }}"
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    state: present
    validate_certs: "no"

- name: Add Filebeat repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ es_major_version }}/apt stable main'
    state: present
    update_cache: true
  when: not es_is_oss | bool

- name: Add Filebeat OSS repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/oss-{{ es_major_version }}/apt stable main'
    state: present
    update_cache: true
  when: es_is_oss | bool

- name: Install Filebeat.
  package:
    name: "filebeat"
    state: present